name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 16.14.2
    - name: install dependencies
      run: npm install
    - name: test local setup
      run: npm run test-setup
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: install dmg-license
      run: npm i dmg-license
    - name: build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run dist-mac
